#include "veyra/codegen.hpp"
#include <regex>
#include <iostream>

namespace veyra {

CodeGen::CodeGen() {}

void CodeGen::indent() {
    for (int i = 0; i < indent_level_; ++i) {
        out_ << "    ";
    }
}

std::string CodeGen::translate_type(const std::string& vtype) {
    if (vtype.empty()) return "auto";
    std::string t = vtype;

    // Pointer / Reference prefix handling: *int -> int64_t*, &int -> int64_t&
    bool is_ptr = false;
    bool is_ref = false;
    while (!t.empty() && (t[0] == '*' || t[0] == '&')) {
        if (t[0] == '*') is_ptr = true;
        if (t[0] == '&') is_ref = true;
        t = t.substr(1);
    }

    // Replace vec[T] with std::vector<T>
    size_t vec_pos;
    while ((vec_pos = t.find("vec[")) != std::string::npos) {
        size_t close_pos = t.find(']', vec_pos);
        if (close_pos != std::string::npos) {
            std::string inner = t.substr(vec_pos + 4, close_pos - (vec_pos + 4));
            t.replace(vec_pos, close_pos - vec_pos + 1, "std::vector<" + translate_type(inner) + ">");
        } else {
            break;
        }
    }

    // Replace map[K, V] with std::unordered_map<K, V>
    size_t map_pos;
    while ((map_pos = t.find("map[")) != std::string::npos) {
        size_t close_pos = t.find(']', map_pos);
        if (close_pos != std::string::npos) {
            std::string inner = t.substr(map_pos + 4, close_pos - (map_pos + 4));
            t.replace(map_pos, close_pos - map_pos + 1, "std::unordered_map<" + inner + ">");
        } else {
            break;
        }
    }

    if (t == "int") t = "int64_t";
    else if (t == "float") t = "double";
    else if (t == "str") t = "std::string";
    else if (t == "bool") t = "bool";
    else if (t == "void") t = "void";

    if (is_ptr) t += "*";
    if (is_ref) t += "&";

    return t;
}

std::string CodeGen::generate(const std::shared_ptr<ProgramNode>& program) {
    out_.str("");
    out_.clear();
    indent_level_ = 0;

    out_ << "// --- Generated by Veyra Compiler (C++20 Target) ---\n";
    out_ << "#include \"veyra/prelude.hpp\"\n\n";

    // Separate includes/cincludes if any
    for (const auto& stmt : program->statements) {
        if (auto inc = std::dynamic_pointer_cast<CIncludeStmt>(stmt)) {
            out_ << "#include " << inc->header << "\n";
        }
    }
    out_ << "\n";

    known_enums_.clear();
    for (const auto& stmt : program->statements) {
        if (auto e = std::dynamic_pointer_cast<EnumDeclStmt>(stmt)) {
            known_enums_.insert(e->name);
        }
    }

    // Forward declare structs and enums
    for (const auto& stmt : program->statements) {
        if (auto s = std::dynamic_pointer_cast<StructDeclStmt>(stmt)) {
            out_ << "struct " << s->name << ";\n";
        } else if (auto e = std::dynamic_pointer_cast<EnumDeclStmt>(stmt)) {
            out_ << "enum class " << e->name << ";\n";
        }
    }
    out_ << "\n";

    bool has_explicit_main = false;
    std::vector<StmtPtr> decls;
    std::vector<StmtPtr> top_level_code;

    for (const auto& stmt : program->statements) {
        if (std::dynamic_pointer_cast<CIncludeStmt>(stmt)) continue;

        if (auto fn = std::dynamic_pointer_cast<FnDeclStmt>(stmt)) {
            if (fn->name == "main") has_explicit_main = true;
            decls.push_back(fn);
        } else if (std::dynamic_pointer_cast<StructDeclStmt>(stmt) || std::dynamic_pointer_cast<EnumDeclStmt>(stmt)) {
            decls.push_back(stmt);
        } else {
            top_level_code.push_back(stmt);
        }
    }

    // Emit all enums, structs and functions first
    for (const auto& d : decls) {
        gen_stmt(d);
    }

    // If there is top-level executable code and no explicit main, wrap into main()
    if (!has_explicit_main && !top_level_code.empty()) {
        out_ << "int main(int argc, char* argv[]) {\n";
        indent_level_++;
        for (const auto& s : top_level_code) {
            gen_stmt(s);
        }
        indent();
        out_ << "return 0;\n";
        indent_level_--;
        out_ << "}\n";
    } else if (has_explicit_main) {
        for (const auto& s : top_level_code) {
            gen_stmt(s);
        }
    }

    return out_.str();
}

void CodeGen::gen_stmt(const StmtPtr& stmt) {
    if (!stmt) return;

    if (auto var = std::dynamic_pointer_cast<VarDeclStmt>(stmt)) {
        indent();
        if (!var->type_annot.empty()) {
            std::string trans_t = translate_type(var->type_annot);
            if (!var->is_mut && trans_t.find('*') == std::string::npos && trans_t.find('&') == std::string::npos) {
                out_ << "const ";
            }
            out_ << trans_t << " " << var->name;
        } else {
            if (var->is_mut) {
                out_ << "auto " << var->name;
            } else {
                out_ << "const auto " << var->name;
            }
        }
        if (var->init_expr) {
            out_ << " = ";
            gen_expr(var->init_expr);
        }
        out_ << ";\n";
    }
    else if (auto enum_decl = std::dynamic_pointer_cast<EnumDeclStmt>(stmt)) {
        indent();
        out_ << "enum class " << enum_decl->name << " {\n";
        indent_level_++;
        for (size_t i = 0; i < enum_decl->members.size(); ++i) {
            indent();
            out_ << enum_decl->members[i].name;
            if (enum_decl->members[i].value) {
                out_ << " = ";
                gen_expr(enum_decl->members[i].value);
            }
            if (i + 1 < enum_decl->members.size()) out_ << ",";
            out_ << "\n";
        }
        indent_level_--;
        indent();
        out_ << "};\n\n";
    }
    else if (auto fn = std::dynamic_pointer_cast<FnDeclStmt>(stmt)) {
        indent();
        if (!fn->generic_params.empty()) {
            out_ << "template <";
            for (size_t i = 0; i < fn->generic_params.size(); ++i) {
                out_ << "typename " << fn->generic_params[i];
                if (i + 1 < fn->generic_params.size()) out_ << ", ";
            }
            out_ << ">\n";
            indent();
        }

        if (fn->is_destructor) {
            out_ << fn->name << "() ";
        } else {
            std::string ret_t = fn->return_type.empty() ? (fn->name == "main" ? "int" : "auto") : translate_type(fn->return_type);
            out_ << ret_t << " " << fn->name << "(";

            for (size_t i = 0; i < fn->params.size(); ++i) {
                const auto& p = fn->params[i];
                if (!p.type_annot.empty()) {
                    std::string trans_t = translate_type(p.type_annot);
                    if (p.is_mut || trans_t.find('&') != std::string::npos || trans_t.find('*') != std::string::npos) {
                        out_ << trans_t << " " << p.name;
                    } else {
                        out_ << "const " << trans_t << "& " << p.name;
                    }
                } else {
                    if (p.is_mut) {
                        out_ << "auto&& " << p.name;
                    } else {
                        out_ << "const auto& " << p.name;
                    }
                }
                if (p.default_val) {
                    out_ << " = ";
                    gen_expr(p.default_val);
                }
                if (i + 1 < fn->params.size()) out_ << ", ";
            }
            out_ << ") ";

            if (fn->is_method && (fn->is_operator || !fn->is_destructor)) {
                out_ << "const ";
            }
            if (fn->is_override) {
                out_ << "override ";
            }
        }

        if (fn->arrow_body) {
            out_ << "{\n";
            indent_level_++;
            indent();
            out_ << "return ";
            gen_expr(fn->arrow_body);
            out_ << ";\n";
            indent_level_--;
            indent();
            out_ << "}\n\n";
        } else if (fn->body) {
            auto block = std::dynamic_pointer_cast<BlockStmt>(fn->body);
            out_ << "{\n";
            indent_level_++;
            if (block) {
                for (const auto& s : block->statements) {
                    gen_stmt(s);
                }
            }
            if (fn->name == "main" && fn->return_type.empty()) {
                indent();
                out_ << "return 0;\n";
            }
            indent_level_--;
            indent();
            out_ << "}\n\n";
        }
    }
    else if (auto sdecl = std::dynamic_pointer_cast<StructDeclStmt>(stmt)) {
        indent();
        if (!sdecl->generic_params.empty()) {
            out_ << "template <";
            for (size_t i = 0; i < sdecl->generic_params.size(); ++i) {
                out_ << "typename " << sdecl->generic_params[i];
                if (i + 1 < sdecl->generic_params.size()) out_ << ", ";
            }
            out_ << ">\n";
            indent();
        }

        out_ << "struct " << sdecl->name;
        if (!sdecl->base_class.empty()) {
            out_ << " : public " << sdecl->base_class;
        }
        out_ << " {\n";
        indent_level_++;

        // Fields
        for (const auto& m : sdecl->members) {
            if (!m.is_method) {
                indent();
                std::string ft = m.type_annot.empty() ? "auto" : translate_type(m.type_annot);
                out_ << ft << " " << m.name;
                if (m.default_val) {
                    out_ << " = ";
                    gen_expr(m.default_val);
                }
                out_ << ";\n";
            }
        }

        // Methods
        for (const auto& m : sdecl->members) {
            if (m.is_method && m.method) {
                out_ << "\n";
                gen_stmt(m.method);
            }
        }

        indent_level_--;
        indent();
        out_ << "};\n\n";
    }
    else if (auto ifst = std::dynamic_pointer_cast<IfStmt>(stmt)) {
        indent();
        out_ << "if (";
        gen_expr(ifst->condition);
        out_ << ") ";
        if (auto b = std::dynamic_pointer_cast<BlockStmt>(ifst->then_branch)) {
            out_ << "{\n";
            indent_level_++;
            for (const auto& s : b->statements) gen_stmt(s);
            indent_level_--;
            indent();
            out_ << "}";
        } else {
            gen_stmt(ifst->then_branch);
        }

        if (ifst->else_branch) {
            out_ << " else ";
            if (auto elif = std::dynamic_pointer_cast<IfStmt>(ifst->else_branch)) {
                gen_stmt(elif);
            } else if (auto b = std::dynamic_pointer_cast<BlockStmt>(ifst->else_branch)) {
                out_ << "{\n";
                indent_level_++;
                for (const auto& s : b->statements) gen_stmt(s);
                indent_level_--;
                indent();
                out_ << "}\n";
            }
        } else {
            out_ << "\n";
        }
    }
    else if (auto whilest = std::dynamic_pointer_cast<WhileStmt>(stmt)) {
        indent();
        out_ << "while (";
        gen_expr(whilest->condition);
        out_ << ") ";
        if (auto b = std::dynamic_pointer_cast<BlockStmt>(whilest->body)) {
            out_ << "{\n";
            indent_level_++;
            for (const auto& s : b->statements) gen_stmt(s);
            indent_level_--;
            indent();
            out_ << "}\n";
        }
    }
    else if (auto for_in = std::dynamic_pointer_cast<ForInStmt>(stmt)) {
        indent();
        if (!for_in->index_name.empty()) {
            out_ << "for (const auto& [" << for_in->index_name << ", " << for_in->var_name << "] : ";
            gen_expr(for_in->iterable);
            out_ << ") ";
        } else {
            if (for_in->is_mut) {
                out_ << "for (auto& " << for_in->var_name << " : ";
            } else {
                out_ << "for (const auto& " << for_in->var_name << " : ";
            }
            gen_expr(for_in->iterable);
            out_ << ") ";
        }

        if (auto b = std::dynamic_pointer_cast<BlockStmt>(for_in->body)) {
            out_ << "{\n";
            indent_level_++;
            for (const auto& s : b->statements) gen_stmt(s);
            indent_level_--;
            indent();
            out_ << "}\n";
        }
    }
    else if (auto for_r = std::dynamic_pointer_cast<ForRangeStmt>(stmt)) {
        indent();
        out_ << "for (int64_t " << for_r->var_name << " = ";
        gen_expr(for_r->start);
        out_ << "; " << for_r->var_name << " < ";
        gen_expr(for_r->stop);
        out_ << "; ++" << for_r->var_name << ") ";
        if (auto b = std::dynamic_pointer_cast<BlockStmt>(for_r->body)) {
            out_ << "{\n";
            indent_level_++;
            for (const auto& s : b->statements) gen_stmt(s);
            indent_level_--;
            indent();
            out_ << "}\n";
        }
    }
    else if (auto ret = std::dynamic_pointer_cast<ReturnStmt>(stmt)) {
        indent();
        out_ << "return";
        if (ret->value) {
            out_ << " ";
            gen_expr(ret->value);
        }
        out_ << ";\n";
    }
    else if (std::dynamic_pointer_cast<BreakStmt>(stmt)) {
        indent();
        out_ << "break;\n";
    }
    else if (std::dynamic_pointer_cast<ContinueStmt>(stmt)) {
        indent();
        out_ << "continue;\n";
    }
    else if (auto raw = std::dynamic_pointer_cast<RawCppStmt>(stmt)) {
        out_ << raw->code << "\n";
    }
    else if (auto ex = std::dynamic_pointer_cast<ExprStmt>(stmt)) {
        indent();
        gen_expr(ex->expr);
        out_ << ";\n";
    }
    else if (auto b = std::dynamic_pointer_cast<BlockStmt>(stmt)) {
        indent();
        out_ << "{\n";
        indent_level_++;
        for (const auto& s : b->statements) gen_stmt(s);
        indent_level_--;
        indent();
        out_ << "}\n";
    }
}

static std::string escape_string(const std::string& in) {
    std::string out;
    for (char c : in) {
        if (c == '\n') out += "\\n";
        else if (c == '\t') out += "\\t";
        else if (c == '\r') out += "\\r";
        else if (c == '"') out += "\\\"";
        else if (c == '\\') out += "\\\\";
        else out += c;
    }
    return out;
}

void CodeGen::gen_expr(const ExprPtr& expr) {
    if (!expr) return;

    if (auto lit = std::dynamic_pointer_cast<LiteralExpr>(expr)) {
        if (lit->lit_type == TokenType::STRING_LITERAL) {
            out_ << "std::string(\"" << escape_string(lit->value) << "\")";
        } else if (lit->lit_type == TokenType::KW_TRUE) {
            out_ << "true";
        } else if (lit->lit_type == TokenType::KW_FALSE) {
            out_ << "false";
        } else if (lit->lit_type == TokenType::KW_NULL) {
            out_ << "nullptr";
        } else {
            out_ << lit->value;
        }
    }
    else if (auto interp = std::dynamic_pointer_cast<StringInterpolationExpr>(expr)) {
        out_ << "([&]() { std::stringstream __ss; ";
        for (const auto& part : interp->parts) {
            if (part.is_expr) {
                out_ << "__ss << (";
                gen_expr(part.expr);
                out_ << "); ";
            } else {
                out_ << "__ss << \"" << escape_string(part.raw_text) << "\"; ";
            }
        }
        out_ << "return __ss.str(); }())";
    }
    else if (auto id = std::dynamic_pointer_cast<IdentifierExpr>(expr)) {
        out_ << id->name;
    }
    else if (auto bin = std::dynamic_pointer_cast<BinaryExpr>(expr)) {
        out_ << "(";
        gen_expr(bin->left);
        out_ << " ";
        switch (bin->op) {
            case TokenType::PLUS: out_ << "+"; break;
            case TokenType::MINUS: out_ << "-"; break;
            case TokenType::STAR: out_ << "*"; break;
            case TokenType::SLASH: out_ << "/"; break;
            case TokenType::PERCENT: out_ << "%"; break;
            case TokenType::ASSIGN: out_ << "="; break;
            case TokenType::PLUS_ASSIGN: out_ << "+="; break;
            case TokenType::MINUS_ASSIGN: out_ << "-="; break;
            case TokenType::STAR_ASSIGN: out_ << "*="; break;
            case TokenType::SLASH_ASSIGN: out_ << "/="; break;
            case TokenType::PERCENT_ASSIGN: out_ << "%="; break;
            case TokenType::EQ: out_ << "=="; break;
            case TokenType::NEQ: out_ << "!="; break;
            case TokenType::LT: out_ << "<"; break;
            case TokenType::GT: out_ << ">"; break;
            case TokenType::LTE: out_ << "<="; break;
            case TokenType::GTE: out_ << ">="; break;
            case TokenType::AND: out_ << "&&"; break;
            case TokenType::OR: out_ << "||"; break;
            default: out_ << "?"; break;
        }
        out_ << " ";
        gen_expr(bin->right);
        out_ << ")";
    }
    else if (auto un = std::dynamic_pointer_cast<UnaryExpr>(expr)) {
        if (un->op == TokenType::NOT) out_ << "!";
        else if (un->op == TokenType::MINUS) out_ << "-";
        else if (un->op == TokenType::PLUS) out_ << "+";
        else if (un->op == TokenType::AMPERSAND) out_ << "&";
        else if (un->op == TokenType::STAR) out_ << "*";
        else if (un->op == TokenType::TILDE) out_ << "~";
        out_ << "(";
        gen_expr(un->operand);
        out_ << ")";
    }
    else if (auto tern = std::dynamic_pointer_cast<TernaryExpr>(expr)) {
        out_ << "(";
        gen_expr(tern->condition);
        out_ << " ? ";
        gen_expr(tern->then_expr);
        out_ << " : ";
        gen_expr(tern->else_expr);
        out_ << ")";
    }
    else if (auto call = std::dynamic_pointer_cast<CallExpr>(expr)) {
        gen_expr(call->callee);
        out_ << "(";
        for (size_t i = 0; i < call->args.size(); ++i) {
            gen_expr(call->args[i]);
            if (i + 1 < call->args.size()) out_ << ", ";
        }
        out_ << ")";
    }
    else if (auto mem = std::dynamic_pointer_cast<MemberAccessExpr>(expr)) {
        if (auto id = std::dynamic_pointer_cast<IdentifierExpr>(mem->object)) {
            if (known_enums_.find(id->name) != known_enums_.end()) {
                out_ << id->name << "::" << mem->member;
                return;
            }
        }
        gen_expr(mem->object);
        out_ << "." << mem->member;
    }
    else if (auto idx = std::dynamic_pointer_cast<IndexExpr>(expr)) {
        gen_expr(idx->object);
        out_ << "[";
        gen_expr(idx->index);
        out_ << "]";
    }
    else if (auto vlit = std::dynamic_pointer_cast<VectorLiteralExpr>(expr)) {
        out_ << "std::vector{";
        for (size_t i = 0; i < vlit->elements.size(); ++i) {
            gen_expr(vlit->elements[i]);
            if (i + 1 < vlit->elements.size()) out_ << ", ";
        }
        out_ << "}";
    }
}

} // namespace veyra
